# ASP.NET
# Build ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
- group: TechChallenge
- name: solution
  value: '**/*.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: ConnectionStrings.SQLServer
  value: '$(ConnectionStringsSQLServer)'

steps:

- task: FileTransform@1
  inputs:
    folderPath: 'TechChallenge.Aplicacao/**/'
    fileType: 'json'
    targetFiles: 'appsettings.json'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Assinatura do Visual Studio Enterprise(000e36a5-1c0b-46d1-b901-554b373cdaec)'
    appType: 'webApp'
    appName: 'fiapcd'
    # package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    package: '$(Build.ArtifactStagingDirectory)'
    deploymentMethod: 'auto'
